# Generated by Django 4.1 on 2023-07-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0002_alter_livroinfo_autor_alter_livroinfo_emprestado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livroinfo",
            name="autor",
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name="livroinfo",
            name="emprestado",
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name="livroinfo",
            name="genero",
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name="livroinfo",
            name="nome",
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name="livroinfo",
            name="xerox",
            field=models.CharField(max_length=264),
        ),
    ]
