# Generated by Django 4.1 on 2023-07-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0003_alter_livroinfo_autor_alter_livroinfo_emprestado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livroinfo",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
