# Generated by Django 4.1 on 2023-07-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0004_livroinfo_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livroinfo",
            name="foto",
            field=models.ImageField(
                null=True, upload_to="DestravaLeitura/files/bookimages"
            ),
        ),
    ]
