# Generated by Django 4.1 on 2023-07-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0005_alter_livroinfo_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livroinfo",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
